url: https://letwearego.github.io

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

plugins:
  - jekyll-feed

collections:
  posts:
    permalink: /:year/:month/:day/:title/

timezone: Asia/Shanghai
title: LETWEAREGO
description: Welcome to my new blog!
